# Expt. 1: Manipulating Single and Multidimensional Arrays using Numpy

In [ ]:
# NumPy (Numerical Python) is a powerful open-source library in Python for numerical and scientific computing. 
# It provides support for arrays, matrices, and a variety of mathematical functions to operate on these data structures. 

## Creating Arrays from Scratch

In [4]:
import numpy as np

- ### Create a length-10 integer array filled with zeros 

In [9]:
z = np.zeros(10, dtype=int)

In [11]:
print(z)

[0 0 0 0 0 0 0 0 0 0]


- ###   Create a 3x5 floating-point array filled with 1s

In [18]:
o = np.ones((3,5), dtype=float)
type(o[0,0])

numpy.float64

In [12]:
print(o)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


- ###   Create a 3x3 identity matrix 

In [51]:
I3 = np.eye(3)

In [53]:
print(I3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


- ###   Create a 3x5 array filled with 3.14 

In [56]:
pi35 = np.full((3, 5), 3.14)

In [58]:
print(pi35)

[[3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]]


- ### Create an array filled with a linear sequence Starting at 0, ending at 20, stepping by 2

In [61]:
ls = np.arange(0, 20, 2)

In [63]:
print(ls)

[ 0  2  4  6  8 10 12 14 16 18]


- ###   Create an array of five values evenly spaced between 0 and 1 

In [66]:
lsp = np.linspace(0, 1, 5)

In [68]:
print(lsp)

[0.   0.25 0.5  0.75 1.  ]


- ###   Create a 3x3 array of uniformly distributed random values between 0 and 1


In [25]:
xu = np.random.random((3, 3))

In [27]:
print(xu)

[[0.24435336 0.6130231  0.49346356]
 [0.10936225 0.99861476 0.8555111 ]
 [0.46949479 0.80049615 0.03859137]]


- ###   Create a 30x30 array of normally distributed random values with mean 0 and standard deviation 1

In [68]:
xn = np.random.normal(0, 1, (30, 30))

In [70]:
# verify mean and standard deviation
print(np.mean(xn))
print(np.std(xn))

0.01744441317079199
1.0040557436440993


- ###   Create a 3x3 array of random integers in the interval [0, 10)

In [63]:
xi = np.random.randint(0, 10, (3, 3))

In [65]:
print(xi)

[[3 8 2]
 [8 9 8]
 [5 1 1]]


- ###   Create an empty array 

In [ ]:
# the values will be garbage - whatever is stored in memory at that time

In [83]:
xe = np.empty((3,4))
print(xe)

[[0.00000000e+000 2.86558075e-322 0.00000000e+000 0.00000000e+000]
 [2.31297541e-312 8.60952352e-072 4.71482719e-090 9.41706372e-047]
 [1.55051041e+184 6.45489107e+170 3.99910963e+252 2.59819083e-306]]


- ### Determining the attributes of numpy arrays

In [96]:
print(xe.dtype)
print(xe.size)
print(xe.shape)
print("itemsize:", xe.itemsize, "bytes")
print("nbytes:", xe.nbytes, "bytes")

float64
12
(3, 4)
itemsize: 8 bytes
nbytes: 96 bytes


## Creating Arrays from lists

In [93]:
import numpy as np

# Creating a 1D array
array_1d = np.array([1, 2, 3])

# Creating a 2D array
array_2d = np.array([[10, 20, 30], [40, 50, 60]])


## Array Indexing and Slicing

In [95]:
# Indexing in 1D array
print("\nElement at index 2 in 1D array:", array_1d[2])

# Slicing in 1D array
print("Elements from index 1 to 3 in 1D array:", array_1d[1:4])

# Indexing in 2D array
print("\nElement at row 1, column 2 in 2D array:", array_2d[1, 2])

# Slicing in 2D array
print("Elements in first two rows and columns 1 and 2:")
print(array_2d[:2, 1:3])


Element at index 2 in 1D array: 3
Elements from index 1 to 3 in 1D array: [2 3]

Element at row 1, column 2 in 2D array: 60
Elements in first two rows and columns 1 and 2:
[[20 30]
 [50 60]]


## Array Operations

In [26]:
#  addition of a scalor
array_add = array_1d + 10
print("\nadding 10 to 1D array:")
print(array_add)

#  multiplication by a scalor
array_mul = array_2d * 2
print("\nmultiply by 2 to 2D array:")
print(array_mul)


adding 10 to 1D array:
[11 12 13]

multiply by 2 to 2D array:
[[ 20  40  60]
 [ 80 100 120]]


## Array Broadcasting in NumPy

In [4]:
# Broadcasting is a powerful mechanism that allows NumPy to perform element-wise operations on arrays of different shapes. 
# It enables arithmetic operations between arrays of different shapes by virtually 
# expanding the smaller array to match the shape of the larger array without actually copying data.

In [12]:
# Broadcasting the 1D array to match the 2D array
result = array_2d + array_1d
print("Result of broadcasting 1D array to 2D array:")
print(result)

Result of broadcasting 1D array to 2D array:
[[11 22 33]
 [41 52 63]]


## Reshaping and Flattening Arrays

In [73]:
# Reshaping 1D array to 2D array
array_reshaped = array_1d.reshape((1, 3))
print("\nReshaped 1D array to 2D array:")
print(array_reshaped)

# Create a 4x5 matrix with random integers
matrix = np.random.randint(1, 10, (4, 5))
print("Original 4x5 matrix:")
print(matrix)

# Reshape the 4x5 matrix to a 10x2 matrix
reshaped_matrix = matrix.reshape(10, 2)
print("\nReshaped 10x2 matrix:")
print(reshaped_matrix)

# Flattening 2D array to 1D array
array_flattened = array_2d.flatten()
print("\nFlattened 2D array to 1D array:")
print(array_flattened)



Reshaped 1D array to 2D array:
[[1 2 3]]
Original 4x5 matrix:
[[8 7 6 7 4]
 [4 8 2 5 7]
 [2 8 3 5 4]
 [7 9 2 4 8]]

Reshaped 10x2 matrix:
[[8 7]
 [6 7]
 [4 4]
 [8 2]
 [5 7]
 [2 8]
 [3 5]
 [4 7]
 [9 2]
 [4 8]]

Flattened 2D array to 1D array:
[10 20 30 40 50 60]


## Combining Arrays

In [17]:
# Vertical stack
array_vstack = np.vstack((array_1d, array_1d))
print("\nVertical Stack of 1D array:")
print(array_vstack)

# Horizontal stack
array_hstack = np.hstack((array_1d, array_1d))
print("\nHorizontal Stack of 1D array:")
print(array_hstack)



Vertical Stack of 1D array:
[[1 2 3]
 [1 2 3]]

Horizontal Stack of 1D array:
[1 2 3 1 2 3]


## Mathematical Operations on Arrays

- ### Element wise operations on two arrays

In [20]:
# you may perform point by point arithmetic operations by using +,-,* and / operators
# for this the dimensions of the arrays being performed must be same
import numpy as np

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

sum_array = array1 + array2       # Element-wise addition
diff_array = array1 - array2      # Element-wise subtraction
product_array = array1 * array2   # Element-wise multiplication
quotient_array = array1 / array2  # Element-wise division
print(sum_array)

[5 7 9]


- ### Dot product

In [26]:
dot_product = np.dot(array1, array2)
print(dot_product)

32


In [35]:
### Matrix Multiplication
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

matrix_product = np.matmul(matrix1, matrix2)
print(matrix_product)

[[19 22]
 [43 50]]


- ### Statistcal Operations

In [57]:
mean_value = np.mean(array1)
median_value = np.median(array1)
std_deviation = np.std(array1)
total_sum = np.sum(array1)
cum_sum = np.cumsum(array1)
min_value = np.min(array1)
max_value = np.max(array1)
print(f"sum = {total_sum}, mean = {mean_value}, median = {median_value}, standard deviation = {std_deviation}")
print(f"minimum = {min_value}, maximum = {max_value}")
print(cum_sum)


sum = 6, mean = 2.0, median = 2.0, standard deviation = 0.816496580927726
minimum = 1, maximum = 3
[1 3 6]


- ### Logical Opeartions

In [59]:
comparison = array1 > 2
logical_and = np.logical_and(array1 > 1, array2 < 6)
logical_or = np.logical_or(array1 < 2, array2 > 4)
print(comparison)
print(logical_and)
print(logical_or)

[False False  True]
[False  True False]
[ True  True  True]


- ### Linear Algebra Operations on Arrays

In [69]:
import numpy as np

# Creating integer array (2-D array)
int_array = np.random.randint(1, 100, size=(3, 3))

# Creating float array (2-D array)
float_array = np.random.random((3, 3))

print("Integer Array:")
print(int_array)

print("\nFloat Array:")
print(float_array)

# Dot Product
print("\n--- Dot Product ---")
dot_product = np.dot(int_array, int_array)
print("\nDot product of integer array with itself:")
print(dot_product)

# Matrix Multiplication
print("\n--- Matrix Multiplication ---")
matrix_multiplication = np.matmul(int_array, float_array)
print("\nMatrix multiplication of integer array with float array:")
print(matrix_multiplication)

# Matrix multiplication using @ operator
matrix_multiplication_at = int_array @ float_array
print("\nMatrix multiplication using @ operator:")
print(matrix_multiplication_at)

# Determinant
print("\n--- Determinant ---")
determinant_int = np.linalg.det(int_array)
determinant_float = np.linalg.det(float_array)
print("\nDeterminant of integer array:")
print(determinant_int)
print("\nDeterminant of float array:")
print(determinant_float)

# Inverse
print("\n--- Inverse ---")
inverse_int = np.linalg.inv(int_array)
inverse_float = np.linalg.inv(float_array)
print("\nInverse of integer array:")
print(inverse_int)
print("\nInverse of float array:")
print(inverse_float)

# Eigenvalues and Eigenvectors
print("\n--- Eigenvalues and Eigenvectors ---")
eigenvalues_int, eigenvectors_int = np.linalg.eig(int_array)
eigenvalues_float, eigenvectors_float = np.linalg.eig(float_array)
print("\nEigenvalues of integer array:")
print(eigenvalues_int)
print("\nEigenvectors of integer array:")
print(eigenvectors_int)
print("\nEigenvalues of float array:")
print(eigenvalues_float)
print("\nEigenvectors of float array:")
print(eigenvectors_float)


Integer Array:
[[41 70 19]
 [75 16 42]
 [30 51 34]]

Float Array:
[[0.09537898 0.74989384 0.88042468]
 [0.75514478 0.27058141 0.74759311]
 [0.80770673 0.41991634 0.91614173]]

--- Dot Product ---

Dot product of integer array with itself:
[[7501 4959 4365]
 [5535 7648 3525]
 [6075 4650 3868]]

--- Matrix Multiplication ---

Matrix multiplication of integer array with float array:
[[ 72.1171004   57.6647566  105.83562278]
 [ 53.15942245  78.20782674 116.4712937 ]
 [ 68.83578177  50.57362277  95.68880802]]

Matrix multiplication using @ operator:
[[ 72.1171004   57.6647566  105.83562278]
 [ 53.15942245  78.20782674 116.4712937 ]
 [ 68.83578177  50.57362277  95.68880802]]

--- Determinant ---

Determinant of integer array:
-92263.0

Determinant of float array:
0.014486582619305756

--- Inverse ---

Inverse of integer array:
[[ 1.73200525e-02  1.52932378e-02 -2.85704996e-02]
 [ 1.39817695e-02 -8.93099075e-03  3.21905856e-03]
 [-3.62550535e-02 -9.75472291e-05  4.97924412e-02]]

Inverse of f